### ISSUE TITLE
Latest 2.0.18-SNAPSHOT breaks Thymeleaf Security

### ISSUE THREAD

**Issue by dharrigan** [thymeleaf/thymeleaf-extras-springsecurity#8]
Hi,

Latest snapshot breaks this module:

```
2013-06-21 07:28:03.330:WARN:oejs.ServletHandler:/consumer/dashboard/details
java.lang.NoSuchMethodError: org.thymeleaf.util.StringUtils.isEmpty(Ljava/lang/Object;)Ljava/lang/Boolean;
    at org.thymeleaf.extras.springsecurity3.dialect.processor.AuthorizeAttrProcessor.isVisible(AuthorizeAttrProcessor.java:78)
    at org.thymeleaf.processor.attr.AbstractConditionalVisibilityAttrProcessor.processAttribute(AbstractConditionalVisibilityAttrProcessor.java:58)
    at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:74)
    at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
```

-=david=-

**Comment by danielfernandez** [comment]
Fixed now. Mistakenly changed the signature of a now-deprecated method. Thanks.

**Comment by dharrigan** [comment]
w00t :)

**Comment by grgrzybek** [comment]
Hi

I still have the same problem with thymeleaf-extras-springsecurity3-2.0.0.jar and thymeleaf-2.1.0-m1.jar...

```
java.lang.NoSuchMethodError: org.thymeleaf.util.StringUtils.isEmpty(Ljava/lang/Object;)Ljava/lang/Boolean;
    org.thymeleaf.extras.springsecurity3.dialect.processor.AuthorizeAttrProcessor.isVisible(AuthorizeAttrProcessor.java:78)
    org.thymeleaf.processor.attr.AbstractConditionalVisibilityAttrProcessor.processAttribute(AbstractConditionalVisibilityAttrProcessor.java:58)
    org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:75)
    org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    org.thymeleaf.dom.Node.applyNextProcessor(Node.java:894)
    org.thymeleaf.dom.Node.processNode(Node.java:849)
```

**Comment by dharrigan** [comment]
Hi,

I'm not seeing this issue on my system with the latest update (not using 2.1.0-m1, just the now released 2.0.18).

-=david=-

**Comment by grgrzybek** [comment]
With 2.0.18 it works. With 2.1.0-m1 not...
Also 2.1.0-m1's org.thymeleaf.util.StringUtils.isEmpty(String) returns primitive `boolean`, not `java.lang.Boolean` so I think `org.thymeleaf.extras:thymeleaf-extras-springsecurity3` should be adapted to 2.1.0-m1...

regards
Grzegorz Grzybek

**Comment by dharrigan** [comment]
Perhaps the changes haven't been merged/rebased into 2.1.0-m1 yet?

I would create a new issue, targetted towards the 2.1.0-m1 release with a stack dump of what you are observing.

-=david=-

**Comment by grgrzybek** [comment]
Thanks a lot for response!

**Comment by danielfernandez** [comment]
Please, note that when using thymeleaf 2.1.x (2.1.0-SNAPSHOT or 2.1.0-mx milestone), you should be using the corresponding 2.1.0-SNAPSHOT version in thymeleaf-extras-springsecurity3 (no milestone versions for this one).

Anyway, I'm removing the dependency on that `isEmpty/isEmptyOrWhitespace` method in order to avoid further problems.
